<?php

return [
    // ===== NAM (50) =====
    ['name' => 'Nguyễn Văn An', 'gender' => 1],
    ['name' => 'Trần Minh Quân', 'gender' => 1],
    ['name' => 'Lê Hoàng Nam', 'gender' => 1],
    ['name' => 'Phạm Quốc Huy', 'gender' => 1],
    ['name' => 'Võ Thành Đạt', 'gender' => 1],
    ['name' => 'Bùi Đức Anh', 'gender' => 1],
    ['name' => 'Đặng Thanh Tùng', 'gender' => 1],
    ['name' => 'Ngô Minh Trí', 'gender' => 1],
    ['name' => 'Huỳnh Nhật Long', 'gender' => 1],
    ['name' => 'Phan Gia Bảo', 'gender' => 1],

    ['name' => 'Nguyễn Hoàng Phúc', 'gender' => 1],
    ['name' => 'Trần Anh Tuấn', 'gender' => 1],
    ['name' => 'Lê Quang Khải', 'gender' => 1],
    ['name' => 'Phạm Minh Khoa', 'gender' => 1],
    ['name' => 'Võ Quốc Thịnh', 'gender' => 1],
    ['name' => 'Bùi Thanh Phong', 'gender' => 1],
    ['name' => 'Đặng Công Danh', 'gender' => 1],
    ['name' => 'Ngô Tiến Đạt', 'gender' => 1],
    ['name' => 'Huỳnh Đức Tài', 'gender' => 1],
    ['name' => 'Phan Minh Nhật', 'gender' => 1],

    ['name' => 'Nguyễn Thành Trung', 'gender' => 1],
    ['name' => 'Trần Quốc Bảo', 'gender' => 1],
    ['name' => 'Lê Minh Hiếu', 'gender' => 1],
    ['name' => 'Phạm Hoàng Long', 'gender' => 1],
    ['name' => 'Võ Anh Dũng', 'gender' => 1],
    ['name' => 'Bùi Nhật Hào', 'gender' => 1],
    ['name' => 'Đặng Minh Sang', 'gender' => 1],
    ['name' => 'Ngô Quốc Việt', 'gender' => 1],
    ['name' => 'Huỳnh Thành Nhân', 'gender' => 1],
    ['name' => 'Phan Thanh Hải', 'gender' => 1],

    ['name' => 'Nguyễn Quang Vinh', 'gender' => 1],
    ['name' => 'Trần Minh Đức', 'gender' => 1],
    ['name' => 'Lê Quốc Toàn', 'gender' => 1],
    ['name' => 'Phạm Anh Khoa', 'gender' => 1],
    ['name' => 'Võ Minh Trường', 'gender' => 1],
    ['name' => 'Bùi Thanh Bình', 'gender' => 1],
    ['name' => 'Đặng Quốc Khánh', 'gender' => 1],
    ['name' => 'Ngô Hoàng Sơn', 'gender' => 1],
    ['name' => 'Huỳnh Minh Tân', 'gender' => 1],
    ['name' => 'Phan Quốc Hưng', 'gender' => 1],

    // ===== NỮ (50) =====
    ['name' => 'Trần Thị Mai', 'gender' => 0],
    ['name' => 'Nguyễn Ngọc Anh', 'gender' => 0],
    ['name' => 'Lê Thị Thu Hà', 'gender' => 0],
    ['name' => 'Phạm Thanh Tuyền', 'gender' => 0],
    ['name' => 'Võ Mỹ Linh', 'gender' => 0],
    ['name' => 'Bùi Thị Kim Ngân', 'gender' => 0],
    ['name' => 'Đặng Thị Thảo', 'gender' => 0],
    ['name' => 'Ngô Thanh Trúc', 'gender' => 0],
    ['name' => 'Huỳnh Ngọc Diễm', 'gender' => 0],
    ['name' => 'Phan Thị Hồng Nhung', 'gender' => 0],

    ['name' => 'Nguyễn Thị Bích Ngọc', 'gender' => 0],
    ['name' => 'Trần Thị Thuỳ Dung', 'gender' => 0],
    ['name' => 'Lê Thị Minh Châu', 'gender' => 0],
    ['name' => 'Phạm Thị Thanh Tâm', 'gender' => 0],
    ['name' => 'Võ Thị Ngọc Hân', 'gender' => 0],
    ['name' => 'Bùi Thị Ánh Tuyết', 'gender' => 0],
    ['name' => 'Đặng Thị Kiều Oanh', 'gender' => 0],
    ['name' => 'Ngô Thị Thanh Loan', 'gender' => 0],
    ['name' => 'Huỳnh Thị Bảo Trân', 'gender' => 0],
    ['name' => 'Phan Thị Minh Thư', 'gender' => 0],

    ['name' => 'Nguyễn Thị Phương Linh', 'gender' => 0],
    ['name' => 'Trần Thị Ngọc Bích', 'gender' => 0],
    ['name' => 'Lê Thị Thu Trang', 'gender' => 0],
    ['name' => 'Phạm Thị Mỹ Duyên', 'gender' => 0],
    ['name' => 'Võ Thị Hoài An', 'gender' => 0],
    ['name' => 'Bùi Thị Thanh Vân', 'gender' => 0],
    ['name' => 'Đặng Thị Yến Nhi', 'gender' => 0],
    ['name' => 'Ngô Thị Kim Chi', 'gender' => 0],
    ['name' => 'Huỳnh Thị Thanh Mai', 'gender' => 0],
    ['name' => 'Phan Thị Tuyết Nhung', 'gender' => 0],

    ['name' => 'Nguyễn Thị Gia Hân', 'gender' => 0],
    ['name' => 'Trần Thị Thanh Trà', 'gender' => 0],
    ['name' => 'Lê Thị Khánh Vy', 'gender' => 0],
    ['name' => 'Phạm Thị Thúy An', 'gender' => 0],
    ['name' => 'Võ Thị Minh Nguyệt', 'gender' => 0],
    ['name' => 'Bùi Thị Bảo Ngọc', 'gender' => 0],
    ['name' => 'Đặng Thị Ngọc Huyền', 'gender' => 0],
    ['name' => 'Ngô Thị Thanh Hương', 'gender' => 0],
    ['name' => 'Huỳnh Thị Kim Anh', 'gender' => 0],
    ['name' => 'Phan Thị Mỹ Linh', 'gender' => 0],
];
